language: node_js
node_js:
  - "6.1"

cache:
  directories:
    - node_modules
    - jspm_packages
    - typings

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jspm install
  - typings install

script:
  - node_modules/.bin/gulp build
  #- node_modules/.bin/gulp test --travis --singleRun